### ISSUE TITLE
How to bridge the connection ?

### ISSUE THREAD

**Issue by LogeswaranA** [deebloo/acurite-weather#58]
Hi There - 
Thank you for the nice project, which is what I was looking for to read the data from Acurite weather station. I am new to this language, so bit not sure where the interlink is happening between the unit and program.
Would be great if there is any direction on that?
I am using this product ->  AcuRite Iris (5-in-1) Home Weather Station with Wi-Fi Connection to Weather Underground with Temperature, Humidity, Wind Speed/Direction, and Rainfall (01540M)

Should I purchase, "display unit" separately? Also, in this repo where do I bridge my unit.

Please advise...and many thanks for the work

**Comment by deebloo** [comment]
@LogeswaranA I just recently updated this to use rtl_433 with a software defined radio receiver. You can get one on Amazon for like 20 bucks if you don't want to buy an indoor console.
